name: powershell / main

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, windows-2022]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Run exercism/powershell ci (runs tests) for all exercises
        shell: pwsh
        run: bin/run-tests.ps1
